on:
  push:
    branches:
      - main

name: Build and deploy to AWS

permissions:
      id-token: write

jobs:
  setup-cache-and-install:
    name: Build and deploy to AWS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.0
  
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install dependencies
        run: pnpm install
  
      - name: Build
        run: pnpx lerna run build

      - name: Deploy to AWS
        run: pnpx lerna run cdk:deploy:all
        env:
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
